"""Importer safety tests use disposable repositories, never real corpus data."""

import importlib.util
import json
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET

import pytest

MODULE = Path(__file__).resolve().parents[1] / "scripts/data_conversion/import_primary_txt.py"
spec = importlib.util.spec_from_file_location("primary_txt_import", MODULE)
importer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(importer)

TEXT = '=N(" nu ")\nIP-MAT,N,L000006a,LOG,nu\nID,BS.1\n'
DICT = '---------------------------------------------------\n=== L000006a\n.FORM\tnu\n.GLOSS\tNEG\n'


def command(repo, *args):
    return subprocess.run(["git", "-c", f"safe.directory={repo.as_posix()}", "-C", str(repo), *args],
                          capture_output=True, check=True).stdout


def commit(repo):
    command(repo, "add", ".")
    command(repo, "-c", "user.name=Importer Test", "-c", "user.email=test@example.invalid",
            "commit", "--allow-empty", "-m", "fixture")


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


@pytest.fixture
def repositories(tmp_path):
    root = tmp_path / "coj"
    source = tmp_path / "source"
    for repo in (root, source / "oncoj_source", source / "senmyo_norito_project"):
        repo.mkdir(parents=True)
        command(repo, "init")
        command(repo, "config", "core.autocrlf", "false")
    write(root / ".gitignore", ".primary-txt-import/\n")
    write(source / "oncoj_source/trees/BS.txt", TEXT)
    write(source / "oncoj_source/trees/FK.txt", TEXT.replace("BS.1", "FK.1"))
    write(source / "oncoj_source/saywopimye.txt", DICT)
    write(source / "senmyo_norito_project/EN_SM_trees_table/EN_01.txt", TEXT.replace("BS.1", "EN.1"))
    for repo in (root, source / "oncoj_source", source / "senmyo_norito_project"):
        commit(repo)
    return root, source


def establish(root, source):
    plan = importer.preview(root, source)
    assert not plan["blockers"]
    result = importer.apply(root)
    assert result["replaced"] == 8
    commit(root)
    return plan


def test_preview_only_and_committed_source(repositories):
    root, source = repositories
    write(source / "oncoj_source/trees/BS.txt", "uncommitted broken text")
    plan = importer.preview(root, source)
    assert not plan["blockers"]
    assert not (root / "data").exists()
    assert len(plan["files"]) == 4
    staged = next(item for item in plan["writes"] if item["target"] == "data/txt/trees/BS.txt")
    assert (root / staged["payload"]).read_text(encoding="utf-8") == TEXT
    assert (source / "oncoj_source/trees/BS.txt").read_text() == "uncommitted broken text"


def test_incremental_conversion_and_noop(repositories, monkeypatch):
    root, source = repositories
    establish(root, source)
    calls = []
    original = importer.convert
    def tracked(*args):
        calls.append(args[0])
        return original(*args)
    monkeypatch.setattr(importer, "convert", tracked)
    plan = importer.preview(root, source)
    assert plan["writes"] == []
    assert calls == []
    assert importer.apply(root) == {"replaced": 0, "manifest_updated": False}
    write(source / "oncoj_source/trees/BS.txt", TEXT.replace(",nu", ",no"))
    commit(source / "oncoj_source")
    untouched = root / "data/xml/trees/FK.xml"
    before = untouched.stat().st_mtime_ns
    plan = importer.preview(root, source)
    assert calls == ["data/txt/trees/BS.txt"]
    assert {item["target"] for item in plan["writes"]} == {"data/txt/trees/BS.txt", "data/xml/trees/BS.xml"}
    importer.apply(root)
    assert untouched.stat().st_mtime_ns == before
    assert (root / "data/txt/trees/BS.txt").read_text() == TEXT.replace(",nu", ",no")
    assert "no" in (root / "data/xml/trees/BS.xml").read_text()


def test_converter_change_requires_full_regeneration(repositories):
    root, source = repositories
    establish(root, source)
    importer.preview(root, source)
    write(root / "src/coj/core/test.py", "# converter fingerprint change\n")
    with pytest.raises(importer.ImportFailure, match="Conversion code changed"):
        importer.apply(root)
    plan = importer.preview(root, source)
    assert plan["full_xml_regeneration"]
    assert all(item["xml_regenerated"] for item in plan["files"].values())
    assert not plan["writes"]  # Equal generated bytes are not replaced.


@pytest.mark.parametrize("committed", [False, True])
def test_local_edits_block_even_when_committed(repositories, committed):
    root, source = repositories
    establish(root, source)
    write(root / "data/xml/trees/BS.xml", "local manual edit")
    if committed:
        commit(root)
    plan = importer.preview(root, source)
    assert any("data/xml/trees/BS.xml" in item for item in plan["blockers"])
    with pytest.raises(importer.ImportFailure, match="blocked"):
        importer.apply(root)
    assert (root / "data/xml/trees/BS.xml").read_text() == "local manual edit"


def test_deletion_is_reported_and_not_applied(repositories):
    root, source = repositories
    establish(root, source)
    (source / "oncoj_source/trees/FK.txt").unlink()
    commit(source / "oncoj_source")
    plan = importer.preview(root, source)
    assert "data/txt/trees/FK.txt" in plan["removed"]
    assert "data/xml/trees/FK.xml" in plan["removed"]
    with pytest.raises(importer.ImportFailure, match="blocked"):
        importer.apply(root)
    assert (root / "data/txt/trees/FK.txt").exists()


def test_source_commit_changed_after_preview(repositories):
    root, source = repositories
    importer.preview(root, source)
    commit(source / "oncoj_source")
    with pytest.raises(importer.ImportFailure, match="Source commit changed"):
        importer.apply(root)
    assert not (root / "data").exists()


def test_local_file_changed_after_preview(repositories):
    root, source = repositories
    establish(root, source)
    importer.preview(root, source)
    write(root / "data/txt/trees/BS.txt", "local edit")
    with pytest.raises(importer.ImportFailure, match="managed file|Local change"):
        importer.apply(root)


def test_tampered_payload_and_path_are_rejected(repositories):
    root, source = repositories
    plan = importer.preview(root, source)
    (root / plan["writes"][0]["payload"]).write_bytes(b"tampered")
    with pytest.raises(importer.ImportFailure, match="Staged content changed"):
        importer.apply(root)
    with pytest.raises(importer.ImportFailure, match="escapes"):
        importer.destination(root, "../outside.txt")


@pytest.mark.parametrize("existing", [False, True])
def test_partial_apply_rolls_back(repositories, monkeypatch, existing):
    root, source = repositories
    if existing:
        establish(root, source)
        write(source / "oncoj_source/trees/BS.txt", TEXT.replace(",nu", ",no"))
        commit(source / "oncoj_source")
    before = {path.relative_to(root): path.read_bytes() for path in (root / "data").rglob("*") if path.is_file()}
    importer.preview(root, source)
    replace = importer.os.replace
    attempts = 0
    def failing_replace(src, dst):
        nonlocal attempts
        if Path(dst).suffix in (".txt", ".xml"):
            attempts += 1
            if attempts == 2:
                raise OSError("simulated write failure")
        return replace(src, dst)
    monkeypatch.setattr(importer.os, "replace", failing_replace)
    with pytest.raises(OSError, match="simulated"):
        importer.apply(root)
    after = {path.relative_to(root): path.read_bytes() for path in (root / "data").rglob("*") if path.is_file()}
    assert after == before
    journal = json.loads((root / importer.CACHE / "transaction.json").read_text())
    assert journal["status"] == "rolled_back"


def test_interrupted_apply_blocks_further_work(repositories):
    root, source = repositories
    write(root / importer.CACHE / "transaction.json", '{"status":"applying"}')
    with pytest.raises(importer.ImportFailure, match="interrupted"):
        importer.preview(root, source)


def test_empty_source_conversion_blocks_apply(repositories):
    root, source = repositories
    write(source / "oncoj_source/trees/BS.txt", "")
    commit(source / "oncoj_source")
    plan = importer.preview(root, source)
    assert any("Conversion validation failed" in item for item in plan["blockers"])
    assert not (root / "data").exists()


def test_dictionary_only_and_provenance_only_updates(repositories):
    root, source = repositories
    establish(root, source)
    write(source / "oncoj_source/saywopimye.txt", DICT.replace("NEG", "negative"))
    commit(source / "oncoj_source")
    plan = importer.preview(root, source)
    assert [path for path, record in plan["files"].items() if record["xml_regenerated"]] == ["data/txt/dict/dictionary.txt"]
    assert importer.apply(root)["replaced"] == 2
    commit(root)
    commit(source / "oncoj_source")  # New source commit, identical mapped files.
    plan = importer.preview(root, source)
    assert plan["writes"] == []
    assert importer.apply(root) == {"replaced": 0, "manifest_updated": True}


def test_failed_preview_invalidates_previous_plan(repositories):
    root, source = repositories
    importer.preview(root, source)
    with pytest.raises(importer.ImportFailure):
        importer.preview(root, source / "missing")
    with pytest.raises(importer.ImportFailure, match="No valid preview"):
        importer.apply(root)


def test_concurrent_import_is_blocked(repositories):
    root, source = repositories
    with importer.exclusive_import(root):
        with pytest.raises(importer.ImportFailure, match="Another import"):
            importer.preview(root, source)


def test_untracked_managed_file_after_preview_blocks_apply(repositories):
    root, source = repositories
    importer.preview(root, source)
    write(root / "data/txt/trees/new.txt", TEXT)
    with pytest.raises(importer.ImportFailure, match="Uncommitted managed file"):
        importer.apply(root)


@pytest.mark.parametrize("ending", [b"\r\n", b"\r", b"mixed"])
def test_line_ending_only_xml_retained_and_recorded(repositories, ending):
    root, source = repositories
    initial = importer.preview(root, source)
    for item in initial["writes"]:
        path = root / item["target"]
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (root / item["payload"]).read_bytes()
        if path.suffix == ".xml":
            if ending == b"mixed":
                content = content.replace(b"\n", b"\r\n", 1)
            else:
                content = content.replace(b"\n", ending)
        path.write_bytes(content)
    commit(root)  # Simulate existing committed data, without an import manifest.
    before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in (root / "data/xml").rglob("*.xml")}
    plan = importer.preview(root, source)
    assert not plan["blockers"]
    assert not plan["writes"]
    assert all(record["xml_line_endings_only"] for record in plan["files"].values())
    for relative, record in plan["files"].items():
        content = (root / record["xml_path"]).read_bytes()
        generated, _, _ = importer.convert(relative, (root / relative).read_bytes(), record["kind"])
        assert content != generated
        assert importer.normalize_line_endings(content) == importer.normalize_line_endings(generated)
        assert record["xml_sha256"] == importer.digest(content)
        assert record["generated_xml_sha256"] == importer.digest(generated)
        assert record["xml_normalized_sha256"] == importer.digest(importer.normalize_line_endings(content))
    assert importer.apply(root) == {"replaced": 0, "manifest_updated": True}
    assert all((path.read_bytes(), path.stat().st_mtime_ns) == original for path, original in before.items())
    commit(root)
    followup = importer.preview(root, source)
    assert not followup["blockers"]
    assert not followup["writes"]
    assert importer.apply(root) == {"replaced": 0, "manifest_updated": False}


@pytest.mark.parametrize("extra", [b" ", b"\xef\xbb\xbf"])
def test_xml_non_line_ending_differences_not_ignored(repositories, extra):
    root, source = repositories
    initial = importer.preview(root, source)
    for item in initial["writes"]:
        path = root / item["target"]
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (root / item["payload"]).read_bytes()
        if path.suffix == ".xml":
            content = content.replace(b"\n", b"\r\n")
            content = extra + content if extra.startswith(b"\xef") else content + extra
        path.write_bytes(content)
    commit(root)
    plan = importer.preview(root, source)
    assert not plan["blockers"]
    assert len(plan["writes"]) == 4
    assert all(item["target"].endswith(".xml") for item in plan["writes"])
    assert not any(record["xml_line_endings_only"] for record in plan["files"].values())


def test_post_import_line_ending_edit_still_blocked(repositories):
    root, source = repositories
    establish(root, source)
    path = root / "data/xml/trees/BS.xml"
    path.write_bytes(path.read_bytes().replace(b"\n", b"\r\n"))
    commit(root)
    plan = importer.preview(root, source)
    assert any("Local change since last import" in message for message in plan["blockers"])
    with pytest.raises(importer.ImportFailure, match="blocked"):
        importer.apply(root)


def test_line_ending_normalization_does_not_relax_txt_matching(repositories):
    root, source = repositories
    initial = importer.preview(root, source)
    for item in initial["writes"]:
        path = root / item["target"]
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (root / item["payload"]).read_bytes()
        path.write_bytes(content.replace(b"\n", b"\r\n"))
    commit(root)
    plan = importer.preview(root, source)
    assert len(plan["writes"]) == 4
    assert all(item["target"].endswith(".txt") for item in plan["writes"])
    assert all(record["xml_line_endings_only"] for record in plan["files"].values())


def legacy_xml_fixture(root, source):
    initial = importer.preview(root, source)
    for item in initial["writes"]:
        path = root / item["target"]
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (root / item["payload"]).read_bytes()
        if path.suffix == ".xml":
            tree = ET.fromstring(content)
            for node in tree.iter():
                attributes = list(reversed(list(node.attrib.items())))
                node.attrib.clear()
                node.attrib.update(attributes)
            ET.indent(tree, space="    ")
            content = ET.tostring(tree, encoding="utf-8", xml_declaration=True, short_empty_elements=False).replace(b"\n", b"\r\n")
        path.write_bytes(content)
    write(root / "scripteditor/runs/history/data.xml", '<history z="2" a="1"/>')
    write(root / "compreditor/workspace/copy.xml", '<copy z="2" a="1"/>')
    commit(root)
    return initial


def test_ordered_import_then_normalization_and_final_manifest(repositories, monkeypatch):
    root, source = repositories
    legacy_xml_fixture(root, source)
    write(source / "oncoj_source/trees/BS.txt", TEXT.replace(",nu", ",no"))
    commit(source / "oncoj_source")
    before = {path: path.read_bytes() for path in root.rglob("*.xml")}
    plan = importer.preview(root, source, normalize_xml=True)
    assert not plan["blockers"]
    assert {item["target"] for item in plan["writes"]} == {"data/txt/trees/BS.txt", "data/xml/trees/BS.xml"}
    norm = plan["normalization"]
    assert len(norm["files"]) == norm["semantics_verified"] == 4
    assert len(norm["writes"]) == 3
    assert all(path.read_bytes() == content for path, content in before.items())
    replaced = []
    replace = importer.os.replace
    def tracked(src, dst):
        if Path(dst).is_relative_to(root / "data"):
            replaced.append(Path(dst).relative_to(root).as_posix())
        return replace(src, dst)
    monkeypatch.setattr(importer.os, "replace", tracked)
    assert importer.apply(root)["replaced"] == 5
    assert replaced[:2] == [item["target"] for item in plan["writes"]]
    assert replaced[2:-1] == [item["target"] for item in norm["writes"]]
    manifest = json.loads((root / importer.MANIFEST).read_text())
    for path in (root / "data/xml").rglob("*.xml"):
        assert path.read_bytes() == importer.canonical_xml(path.read_bytes())
    for record in manifest["files"].values():
        assert record["xml_sha256"] == importer.digest((root / record["xml_path"]).read_bytes())
    assert (root / "scripteditor/runs/history/data.xml").read_bytes() == before[root / "scripteditor/runs/history/data.xml"]
    assert (root / "compreditor/workspace/copy.xml").read_bytes() == before[root / "compreditor/workspace/copy.xml"]
    commit(root)
    followup = importer.preview(root, source, normalize_xml=True)
    assert not followup["writes"] and not followup["normalization"]["writes"]
    assert importer.apply(root) == {"replaced": 0, "manifest_updated": False}


def test_normalization_payload_tampering_blocks_all_steps(repositories):
    root, source = repositories
    legacy_xml_fixture(root, source)
    plan = importer.preview(root, source, normalize_xml=True)
    payload = plan["normalization"]["writes"][0]["payload"]
    (root / payload).write_bytes(b"tampered")
    with pytest.raises(importer.ImportFailure, match="Staged normalization changed"):
        importer.apply(root)
    assert not (root / importer.MANIFEST).exists()


def test_normalization_failure_rolls_back_import_and_formatting(repositories, monkeypatch):
    root, source = repositories
    legacy_xml_fixture(root, source)
    write(source / "oncoj_source/trees/BS.txt", TEXT.replace(",nu", ",no"))
    commit(source / "oncoj_source")
    plan = importer.preview(root, source, normalize_xml=True)
    before = {path: path.read_bytes() for path in (root / "data").rglob("*") if path.is_file()}
    target = root / plan["normalization"]["writes"][1]["target"]
    replace = importer.os.replace
    failed = False
    def failing(src, dst):
        nonlocal failed
        if Path(dst) == target and not failed:
            failed = True
            raise OSError("normalization failure")
        return replace(src, dst)
    monkeypatch.setattr(importer.os, "replace", failing)
    with pytest.raises(OSError, match="normalization failure"):
        importer.apply(root)
    assert {path: path.read_bytes() for path in (root / "data").rglob("*") if path.is_file()} == before


def test_normalization_inventory_change_blocks_apply(repositories):
    root, source = repositories
    legacy_xml_fixture(root, source)
    importer.preview(root, source, normalize_xml=True)
    write(root / "data/xml/extra/new.xml", '<new/>')
    commit(root)
    with pytest.raises(importer.ImportFailure, match="normalization inventory changed"):
        importer.apply(root)
